{% set name = "cmdstan" %}
{% set version = "2.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86]
  sha256: d944d23ac7ed5ebf924d859f3a1f3052891161e2c70313503f21257ea13f0b0c  # [x86]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [not x86]
  sha256: dde66ccda89929375f9cba554b3dc7745b7220b23c75523e78cc946bdd3e3399  # [not x86]
  patches:  # this can be deleted after next cmdstan release
    - make-tbb-check.patch  # [win]

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
  host:
    - tbb-devel ==2019.8           # [not win]
  run:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - tbb-devel ==2019.8           # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
  run_constrained:
    - tbb >=2021                   # [win]

test:
  downstreams:
    - cmdstanpy

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'CmdStan, the command line interface to Stan'
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
