{% set name = "cmdstan" %}
{% set version = "2.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
    sha256: 3ae8d290fa7ed6a0f425520e525460a159a32653b6d45f2153e1662d82f85f10  # [x86 or arm64]
  - url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
    sha256: aa61eeb43e02d7fd14fb33afb51a8ceb94daca8fb66d48775ac088a5b2264caf  # [aarch64]

build:
  number: 0
  binary_relocation: false
  missing_dso_whitelist:            # [win]
    - "$RPATH/libgcc_s_seh-1.dll"   # [win]
    - "$RPATH/libstdc++-6.dll"      # [win]
    - "$RPATH/libwinpthread-1.dll"  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}         # [not win]
    - make                          # [not win]
    - {{ compiler('ucrt64_cxx') }}  # [win]
    - msys2-make                    # [win]
    - msys2-filesystem              # [win]
    - msys2-sed                     # [win]
    - msys2-coreutils               # [win]
  host:
    - tbb-devel                     # [not win]
    - tbb                           # [win]
  run:
    - {{ compiler('cxx') }}         # [not win]
    - make                          # [not win]
    - tbb-devel                     # [not win]
    - {{ compiler('ucrt64_cxx') }}  # [win]
    - msys2-make                    # [win]
    - msys2-filesystem              # [win]
    - msys2-sed                     # [win]
    - msys2-coreutils               # [win]
  run_constrained:
    - tbb >=2021                    # [win]

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
  skip-lints:
    - missing_hash
    - missing_source
    - compilers_must_be_in_build
    - build_tools_must_be_in_build
